//! Small auxiliary files: offset tables, related-object lists, disambiguation labels and the
//! level-word translation map.

use scribble_core::{Context, Format, Reader, Result, Writer, bail, ensure};
use serde::{Deserialize, Serialize};

/// `*_jumptable_<lang>`, `*_word_id_table_<lang>` and `related_objects_jumptable`: a flat array
/// of absolute byte offsets into the matching dictionary file.
///
/// ```text
/// u32 offset[file_size / 4]     0 = no entry
/// ```
///
/// * `object_jumptable` / `adjective_jumptable` / `tag_jumptable`: indexed by object /
///   adjective / tag id, pointing at the record of the id's display name. `FUN_0073cd60(id,
///   buf, size, kind)` reads `offset = table[id]` and copies that record's word as the name the
///   game shows (hard-coded exceptions for objects: ids `0xb31`, `0x1927` print `MAXWELL`,
///   `0x1bf6`, `0x1c7b` `LILY`, `0x1c70` `EDGAR`, `0x1c71` `JULIE`; `0x1520` uses id `0x291`'s
///   name); `FUN_0073d3d0(id, kind, ...)` returns the record's word id and the resource of its
///   meaning with that id. Resource ids come from `FUN_0073c5c0(kind)` (1 object, 2 adjective,
///   4 tag).
/// * `object_word_id_table` / `adjective_word_id_table` / `tag_word_id_table`: indexed by word id,
///   pointing at that word's record (`FUN_0073d0b0`, `FUN_0073d250`; ids from `FUN_0073c720`).
/// * `related_objects_jumptable`: indexed by object id, pointing into `related_objects_dictionary`.
///
/// All of these are regenerated by [`crate::Dictionary`] / [`crate::RelatedObjects`]; edit
/// those instead of the raw offsets.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OffsetTable {
    pub offsets: Vec<u32>,
}

impl Format for OffsetTable {
    const NAME: &'static str = "offset_table";
    const DESCRIPTION: &'static str = "Id -> record offset table for a dictionary file (jump table / word id table)";

    fn decode(data: &[u8], _ctx: &Context) -> Result<Self> {
        ensure!(data.len().is_multiple_of(4), "offset table size {} is not a multiple of 4", data.len());
        Ok(OffsetTable { offsets: data.chunks_exact(4).map(|c| u32::from_le_bytes(c.try_into().unwrap())).collect() })
    }
    fn encode(&self, _ctx: &Context) -> Result<Vec<u8>> {
        Ok(offsets_to_bytes(&self.offsets))
    }
}

pub(crate) fn offsets_to_bytes(v: &[u32]) -> Vec<u8> {
    v.iter().flat_map(|o| o.to_le_bytes()).collect()
}

/// `related_objects_dictionary`: for each object, the objects the game may suggest/spawn as
/// related ones (`FUN_006bfdc0` picks random entries). Language independent.
///
/// ```text
/// repeated until EOF:
///   u16 count
///   u16 object_id[count]
/// ```
///
/// Lists are addressed through `related_objects_jumptable` (object id -> offset). Lists appear in
/// object-id order; the first list sits at offset 0, which the jump table cannot express (0 means
/// "none"), so in the shipped data it is unreachable. See [`crate::RelatedObjects`] for the
/// combined view with owners.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelatedObjectsLists {
    pub lists: Vec<Vec<u16>>,
}

impl RelatedObjectsLists {
    pub(crate) fn encode_with_offsets(&self) -> Result<(Vec<u8>, Vec<u32>)> {
        let mut w = Writer::new();
        let mut offsets = Vec::with_capacity(self.lists.len());
        for l in &self.lists {
            offsets.push(w.pos() as u32);
            w.u16(u16::try_from(l.len()).map_err(|_| scribble_core::anyhow!("related list too long"))?);
            for &id in l {
                w.u16(id);
            }
        }
        Ok((w.into_inner(), offsets))
    }
    pub(crate) fn decode_with_offsets(data: &[u8]) -> Result<(Self, Vec<u32>)> {
        let mut r = Reader::new(data);
        let mut lists = Vec::new();
        let mut offsets = Vec::new();
        while !r.at_end() {
            offsets.push(r.pos() as u32);
            let n = r.u16()?;
            lists.push((0..n).map(|_| r.u16()).collect::<Result<Vec<_>>>()?);
        }
        Ok((RelatedObjectsLists { lists }, offsets))
    }
}

impl Format for RelatedObjectsLists {
    const NAME: &'static str = "related_objects";
    const DESCRIPTION: &'static str = "Lists of related object ids, addressed by related_objects_jumptable";

    fn decode(data: &[u8], _ctx: &Context) -> Result<Self> {
        Ok(Self::decode_with_offsets(data)?.0)
    }
    fn encode(&self, _ctx: &Context) -> Result<Vec<u8>> {
        Ok(self.encode_with_offsets()?.0)
    }
}

/// `details_file_<lang>`: labels shown when a typed word has several meanings (`ADULT` ->
/// `FEMALE` / `MALE`, `ANCHOR` -> `BOAT` / `MALE` / `FEMALE`). Loaded with the dictionary by
/// `FUN_007472a0` (resource from `FUN_0073c880`).
///
/// ```text
/// u8  n                    number of distinct first letters
/// u8  letter[n]            first letters, in order of first appearance
/// u32 first_entry[n]       absolute offset of the first entry starting with letter[i]
/// entries, sorted by word bytes:
///   u8  word_len, u8 word[word_len]
///   u8  count
///   u16 id[count]          object/adjective ids, same order as the word's meanings
///   count x { u8 label_len, u8 label[label_len] }
/// ```
///
/// There is one entry per multi-meaning word of `object_dictionary_<lang>`, plus a few
/// entries whose word contains an apostrophe (`ARME D'HAST`) that the dictionary stores without it.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Details {
    pub entries: Vec<DetailEntry>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailEntry {
    pub word: String,
    pub choices: Vec<Choice>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Choice {
    /// Object (or adjective) id of the meaning.
    pub id: u16,
    /// Text shown for this meaning.
    pub label: String,
}

impl Format for Details {
    const NAME: &'static str = "details";
    const DESCRIPTION: &'static str = "Choice labels for words with several meanings";

    fn decode(data: &[u8], _ctx: &Context) -> Result<Self> {
        let mut r = Reader::new(data);
        let n = r.u8()? as usize;
        let letters = r.bytes(n)?.to_vec();
        let firsts = (0..n).map(|_| r.u32()).collect::<Result<Vec<_>>>()?;
        let mut entries = Vec::new();
        let mut offsets = Vec::new();
        while !r.at_end() {
            offsets.push(r.pos() as u32);
            let word = r.str_u8()?;
            let count = r.u8()? as usize;
            let ids = (0..count).map(|_| r.u16()).collect::<Result<Vec<_>>>()?;
            let choices = ids.into_iter().map(|id| Ok(Choice { id, label: r.str_u8()? })).collect::<Result<Vec<_>>>()?;
            entries.push(DetailEntry { word, choices });
        }
        let d = Details { entries };
        let (l2, f2) = d.header(&offsets)?;
        ensure!(l2 == letters && f2 == firsts, "details header is not the derived first-letter index");
        Ok(d)
    }

    fn encode(&self, _ctx: &Context) -> Result<Vec<u8>> {
        let mut body = Writer::new();
        let mut rel = Vec::new();
        for e in &self.entries {
            rel.push(body.pos() as u32);
            ensure!(!e.word.is_empty(), "empty word in details");
            body.str_u8(&e.word)?;
            body.u8(u8::try_from(e.choices.len()).map_err(|_| scribble_core::anyhow!("too many choices for {:?}", e.word))?);
            for c in &e.choices {
                body.u16(c.id);
            }
            for c in &e.choices {
                body.str_u8(&c.label)?;
            }
        }
        let (letters, _) = self.header(&rel)?;
        let start = 1 + letters.len() * 5;
        let offsets: Vec<u32> = rel.iter().map(|o| o + start as u32).collect();
        let (letters, firsts) = self.header(&offsets)?;
        let mut w = Writer::new();
        w.u8(letters.len() as u8).bytes(&letters);
        for f in firsts {
            w.u32(f);
        }
        w.bytes(&body.buf);
        Ok(w.into_inner())
    }
}

impl Details {
    fn header(&self, offsets: &[u32]) -> Result<(Vec<u8>, Vec<u32>)> {
        let mut letters = Vec::new();
        let mut firsts = Vec::new();
        for (e, &o) in self.entries.iter().zip(offsets) {
            let c = scribble_core::bin::to_latin1(&e.word)?[0];
            if !letters.contains(&c) {
                letters.push(c);
                firsts.push(o);
            }
        }
        ensure!(letters.len() < 256, "too many first letters");
        Ok((letters, firsts))
    }
}

/// `<lang>.dtm`: translation map from the language-independent word keys stored in level files
/// to this language's word ids. `FUN_0073cac0` maps a placed object's word (table 0) and
/// `FUN_0073cbc0` maps adjective lists (table 1, or table 2 when its last argument is set),
/// all by binary search (`FUN_0073ca00`), so keys must stay ascending; keys `0xFFFF` / `0xFFFE`
/// pass through untranslated. The resource is chosen per language by `FUN_0073cac0`
/// (`0x1e32` english, `0x1e31` dutch, `0x1e35` french, `0x1e36` german, `0x1e37` italian,
/// `0x1e6d` spanish_mexico, `0x1e69` portuguese_brazil).
///
/// ```text
/// 3 x {
///   u16 count
///   count x { u16 key, u32 word_id }
/// }
/// ```
///
/// Languages the engine cannot select have three empty tables.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranslationMap {
    /// Table 0: key -> object word id (index into `object_word_id_table_<lang>`).
    pub object_words: Vec<Translation>,
    /// Table 1: key -> adjective word id (index into `adjective_word_id_table_<lang>`), for the
    /// display words of ordinary adjective lists (`FUN_0053e890`, `FUN_004339c0`,
    /// `FUN_004bc0f0`, `FUN_00545270` call `FUN_0073cbc0(.., 0)`).
    pub adjective_words: Vec<Translation>,
    /// Table 2: key -> adjective word id for the `word_ids` display-word overrides of the
    /// `apply_adjectives` script action (its run function `FUN_0053d590` is the only caller of
    /// `FUN_0073cbc0(.., 1)`).
    pub apply_adjectives_words: Vec<Translation>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Translation {
    pub key: u16,
    pub word_id: u32,
}

impl Format for TranslationMap {
    const NAME: &'static str = "dtm";
    const DESCRIPTION: &'static str = "Level word key -> localized word id translation tables";

    fn decode(data: &[u8], _ctx: &Context) -> Result<Self> {
        let mut r = Reader::new(data);
        let mut table = || -> Result<Vec<Translation>> {
            let n = r.u16()?;
            (0..n).map(|_| Ok(Translation { key: r.u16()?, word_id: r.u32()? })).collect()
        };
        let (a, b, c) = (table()?, table()?, table()?);
        if !r.at_end() {
            bail!("{} trailing bytes after the three translation tables", r.remaining());
        }
        Ok(TranslationMap { object_words: a, adjective_words: b, apply_adjectives_words: c })
    }
    fn encode(&self, _ctx: &Context) -> Result<Vec<u8>> {
        let mut w = Writer::new();
        for t in [&self.object_words, &self.adjective_words, &self.apply_adjectives_words] {
            w.u16(u16::try_from(t.len()).map_err(|_| scribble_core::anyhow!("translation table too long"))?);
            for e in t {
                w.u16(e.key).u32(e.word_id);
            }
        }
        Ok(w.into_inner())
    }
}
