use fmt_dictionary::*;
use scribble_core::testing::{check_all, context, extracted_root, resources};
use scribble_core::ResPath;

const D: &str = "data\\_game\\scribbleobjects\\d";
const A: &str = "data\\_game\\scribbleadjectives\\dictionary";

fn in_d(p: &ResPath) -> bool {
    p.dir == D && p.file != "dictionary.dps"
}

#[test]
fn object_and_tag_dictionaries() {
    let n = check_all::<WordList>(|p| {
        p.dir == D
            && (p.file.starts_with("tag_dictionary_")
                || p.file.strip_prefix("object_dictionary_").is_some_and(|l| !LEGACY_LANGUAGES.contains(&l)))
    });
    assert!(n == 0 || n == 18, "{n}");
}

#[test]
fn legacy_object_dictionaries() {
    let n = check_all::<LegacyObjectDictionary>(|p| {
        p.dir == D && p.file.strip_prefix("object_dictionary_").is_some_and(|l| LEGACY_LANGUAGES.contains(&l))
    });
    assert!(n == 0 || n == 4, "{n}");
}

#[test]
fn legacy_adjective_dictionaries() {
    let n = check_all::<WordList>(|p| p.dir == A && p.file.starts_with("adjective_dictionary_"));
    assert!(n == 0 || n == 12, "{n}");
}

#[test]
fn single_word_indices() {
    let n = check_all::<SingleWordIndex>(|p| p.dir == D && p.file.starts_with("object_single_word_"));
    assert!(n == 0 || n == 9, "{n}");
}

#[test]
fn offset_tables() {
    let n = check_all::<OffsetTable>(|p| {
        (p.dir == D || p.dir == A) && (p.file.contains("_jumptable") || p.file.contains("_word_id_table_"))
    });
    assert!(n == 0 || n == 24 + 13 * 2 + 9 * 4 + 1, "{n}");
}

#[test]
fn related_objects_lists() {
    check_all::<RelatedObjectsLists>(|p| p.dir == D && p.file == "related_objects_dictionary");
}

#[test]
fn details_files() {
    let n = check_all::<Details>(|p| p.dir == D && p.file.starts_with("details_file_"));
    assert!(n == 0 || n == 13, "{n}");
}

#[test]
fn translation_maps() {
    let n = check_all::<TranslationMap>(|p| p.dir == D && p.ext == "dtm");
    assert!(n == 0 || n == 13, "{n}");
}

/// Every file in the two dictionary directories is claimed by `handler` and round-trips
/// through the codec it picks.
#[test]
fn handler_claims_every_file() {
    let files = resources(|p| in_d(p) || p.dir == A);
    if files.is_empty() {
        return;
    }
    let ctx = context();
    assert_eq!(files.len(), 108 + 13 + 36, "file count");
    for (logical, path) in &files {
        let data = std::fs::read(path).unwrap();
        let codec = handler(&ResPath::new(logical), &data).unwrap_or_else(|| panic!("no codec for {logical}"));
        codec.roundtrip(&data, &ctx).unwrap_or_else(|e| panic!("{logical}: {e:#}"));
    }
}

fn originals(files: &[(String, Vec<u8>)]) -> Vec<(String, Vec<u8>)> {
    let root = extracted_root().unwrap();
    files
        .iter()
        .map(|(p, _)| (p.clone(), std::fs::read(p.split('\\').fold(root.clone(), |r, c| r.join(c))).unwrap()))
        .collect()
}

fn assert_same(regenerated: &[(String, Vec<u8>)]) {
    for ((p, got), (_, want)) in regenerated.iter().zip(originals(regenerated)) {
        if *got != want {
            let at = got.iter().zip(&want).position(|(a, b)| a != b).unwrap_or(got.len().min(want.len()));
            panic!("{p}: regenerated bytes differ at {at:#x} (len {} vs {})", got.len(), want.len());
        }
    }
}

/// The high-level model regenerates every derived table byte-for-byte, for every language.
#[test]
fn dictionaries_regenerate_exactly() {
    let Some(root) = extracted_root() else { return };
    let ctx = context();
    let mut total = 0;
    for lang in LANGUAGES {
        let dict = Dictionary::load_dir(&root, lang, &ctx).unwrap_or_else(|e| panic!("{lang}: {e:#}"));
        // The model also survives JSON.
        let json = serde_json::to_string(&dict).unwrap();
        let back: Dictionary = serde_json::from_str(&json).unwrap();
        assert_eq!(back, dict, "{lang}: JSON round trip");
        let files = back.to_files(&ctx).unwrap_or_else(|e| panic!("{lang}: {e:#}"));
        assert_same(&files);
        total += files.len();
    }
    for lang in LegacyAdjectiveDictionary::LANGUAGES {
        let d = LegacyAdjectiveDictionary::load(lang, &ctx, dir_source(&root)).unwrap_or_else(|e| panic!("{lang}: {e:#}"));
        let files = d.to_files(&ctx).unwrap();
        assert_same(&files);
        total += files.len();
    }
    let rel = RelatedObjects::load(dir_source(&root)).unwrap();
    let files = rel.to_files().unwrap();
    assert_same(&files);
    total += files.len();
    // Every file except dictionary.dps is regenerated by a high-level model.
    assert_eq!(total, 108 + 13 + 36, "regenerated file count");
}

#[test]
fn edit_english_dictionary() {
    let Some(root) = extracted_root() else { return };
    let ctx = context();
    let mut dict = Dictionary::load_dir(&root, "english", &ctx).unwrap();

    let cow = dict.find("COW", WordKind::Object).expect("COW").meanings[0].id;
    let cow_res = dict.objects[&cow].properties.resource.clone().unwrap();
    assert_eq!(dict.ids_for_resource(WordKind::Object, &cow_res_path(&cow_res)), vec![cow]);

    // Add a new word naming the cow, a two-meaning word, rename one and remove one.
    let added = dict.add_word("moocow", WordKind::Object, vec![Sense::new(cow)]).unwrap();
    assert_eq!(added, "MOOCOW");
    let horse = dict.find("HORSE", WordKind::Object).unwrap().meanings[0].id;
    dict.add_word(
        "cowhorse",
        WordKind::Object,
        vec![Sense { id: cow, label: Some("COW".into()) }, Sense { id: horse, label: Some("HORSE".into()) }],
    )
    .unwrap();
    dict.rename_word("ZYGOTE", WordKind::Object, "ZYGOTE CELL").unwrap();
    dict.remove_word("ZYZZYVA", WordKind::Object).unwrap();
    let before = dict.words.len();

    let files = dict.to_files(&ctx).unwrap();
    let get = |name: &str| files.iter().find(|(p, _)| p.ends_with(name)).unwrap().1.clone();
    let reread = Dictionary::load(&dict.language, &ctx, |p: &str| Ok(files.iter().find(|(q, _)| q == p).map(|(_, b)| b.clone())))
        .unwrap();

    assert_eq!(reread.words.len(), before);
    let e = reread.find("MOOCOW", WordKind::Object).expect("new word present");
    assert_eq!(e.meanings, vec![Sense::new(cow)]);
    assert_eq!(reread.objects[&cow].properties.resource.as_ref(), Some(&cow_res));
    let e = reread.find("COWHORSE", WordKind::Object).unwrap();
    assert_eq!(e.meanings[1].label.as_deref(), Some("HORSE"));
    assert!(reread.find("ZYGOTE CELL", WordKind::Object).is_some());
    assert!(reread.find("ZYGOTE", WordKind::Object).is_none());
    assert!(reread.find("ZYZZYVA", WordKind::Object).is_none());
    // Level translations still point at the same words even though word ids shifted.
    assert_eq!(reread.translations, dict.translations);
    // The display name of the cow is unchanged.
    assert_eq!(reread.name_of(WordKind::Object, cow), dict.name_of(WordKind::Object, cow));
    // The per-file codecs see the new word too.
    let list = <WordList as scribble_core::Format>::decode(&get("object_dictionary_english"), &ctx).unwrap();
    assert!(list.words.iter().any(|w| w.word == "MOOCOW"));
    let single = <SingleWordIndex as scribble_core::Format>::decode(&get("object_single_word_english"), &ctx).unwrap();
    assert!(single.words.iter().any(|w| w.word == "MOOCOW"));
    assert!(single.words.iter().any(|w| w.word == "CELL"));
    let details = <Details as scribble_core::Format>::decode(&get("details_file_english"), &ctx).unwrap();
    assert!(details.entries.iter().any(|d| d.word == "COWHORSE" && d.choices.len() == 2));
    // And the whole set is again regenerated exactly from what we wrote.
    assert_eq!(reread.to_files(&ctx).unwrap(), files);
}

fn cow_res_path(r: &scribble_core::ResRef) -> String {
    match r {
        scribble_core::ResRef::Path(p) => p.clone(),
        scribble_core::ResRef::Index(i) => panic!("unresolved resource {i}"),
    }
}

#[test]
fn related_objects_edit() {
    let Some(root) = extracted_root() else { return };
    let mut rel = RelatedObjects::load(dir_source(&root)).unwrap();
    assert!(rel.lists[0].object.is_none());
    rel.set_related(7000, vec![1, 2, 3]);
    let (d, j) = rel.to_bytes().unwrap();
    let back = RelatedObjects::from_bytes(&d, &j).unwrap();
    assert_eq!(back.related_to(7000), Some(&[1u16, 2, 3][..]));
}
